const jokesContainer = document.getElementById('jokesContainer');
let page = 1;
const jokesPerPage = 20;
const totalJokes = 200;

// Array of custom jokes (you can add more)
const customJokes = [
    "Joke #1: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #2: Chuck Norris can divide by zero.",
    "Joke #3: Chuck Norris counted to infinity. Twice.",
    "Joke #4: Chuck Norris can slam a revolving door.",
    "Joke #5: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #6: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #7: Chuck Norris doesn't sleep. He waits.",
    "Joke #8: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #9: Chuck Norris can build a snowman out of rain.",
    "Joke #10: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #11: Chuck Norris can hear sign language.",
    "Joke #12: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #13: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #14: Chuck Norris can divide by zero.",
    "Joke #15: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #16: Chuck Norris can slam a revolving door.",
    "Joke #17: Chuck Norris can unscramble an egg.",
    "Joke #18: Chuck Norris can believe it's not butter.",
    "Joke #19: Chuck Norris can hear sign language.",
    "Joke #20: Chuck Norris counted to infinity. Twice.",
    "Joke #21: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #22: Chuck Norris can divide by zero.",
    "Joke #23: Chuck Norris counted to infinity. Twice.",
    "Joke #24: Chuck Norris can slam a revolving door.",
    "Joke #25: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #26: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #27: Chuck Norris doesn't sleep. He waits.",
    "Joke #28: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #29: Chuck Norris can build a snowman out of rain.",
    "Joke #30: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #31: Chuck Norris can hear sign language.",
    "Joke #32: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #33: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #34: Chuck Norris can divide by zero.",
    "Joke #35: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #36: Chuck Norris can slam a revolving door.",
    "Joke #37: Chuck Norris can unscramble an egg.",
    "Joke #38: Chuck Norris can believe it's not butter.",
    "Joke #39: Chuck Norris can hear sign language.",
    "Joke #40: Chuck Norris counted to infinity. Twice.",
    "Joke #41: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #42: Chuck Norris can divide by zero.",
    "Joke #43: Chuck Norris counted to infinity. Twice.",
    "Joke #44: Chuck Norris can slam a revolving door.",
    "Joke #45: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #46: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #47: Chuck Norris doesn't sleep. He waits.",
    "Joke #48: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #49: Chuck Norris can build a snowman out of rain.",
    "Joke #50: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #51: Chuck Norris can hear sign language.",
    "Joke #52: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #53: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #54: Chuck Norris can divide by zero.",
    "Joke #55: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #56: Chuck Norris can slam a revolving door.",
    "Joke #57: Chuck Norris can unscramble an egg.",
    "Joke #58: Chuck Norris can believe it's not butter.",
    "Joke #59: Chuck Norris can hear sign language.",
    "Joke #60: Chuck Norris counted to infinity. Twice.",
    "Joke #61: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #62: Chuck Norris can divide by zero.",
    "Joke #63: Chuck Norris counted to infinity. Twice.",
    "Joke #64: Chuck Norris can slam a revolving door.",
    "Joke #65: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #66: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #67: Chuck Norris doesn't sleep. He waits.",
    "Joke #68: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #69: Chuck Norris can build a snowman out of rain.",
    "Joke #70: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #71: Chuck Norris can hear sign language.",
    "Joke #72: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #73: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #74: Chuck Norris can divide by zero.",
    "Joke #75: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #76: Chuck Norris can slam a revolving door.",
    "Joke #77: Chuck Norris can unscramble an egg.",
    "Joke #78: Chuck Norris can believe it's not butter.",
    "Joke #79: Chuck Norris can hear sign language.",
    "Joke #80: Chuck Norris counted to infinity. Twice.",
    "Joke #81: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #82: Chuck Norris can divide by zero.",
    "Joke #83: Chuck Norris counted to infinity. Twice.",
    "Joke #84: Chuck Norris can slam a revolving door.",
    "Joke #85: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #86: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #87: Chuck Norris doesn't sleep. He waits.",
    "Joke #88: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #89: Chuck Norris can build a snowman out of rain.",
    "Joke #90: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #91: Chuck Norris can hear sign language.",
    "Joke #92: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #93: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #94: Chuck Norris can divide by zero.",
    "Joke #95: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #96: Chuck Norris can slam a revolving door.",
    "Joke #97: Chuck Norris can unscramble an egg.",
    "Joke #98: Chuck Norris can believe it's not butter.",
    "Joke #99: Chuck Norris can hear sign language.",
    "Joke #100: Chuck Norris counted to infinity. Twice.","Joke #101: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #102: Chuck Norris can divide by zero.",
    "Joke #103: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #104: Chuck Norris can slam a revolving door.",
    "Joke #105: Chuck Norris can unscramble an egg.",
    "Joke #106: Chuck Norris can believe it's not butter.",
    "Joke #107: Chuck Norris can hear sign language.",
    "Joke #108: Chuck Norris counted to infinity. Twice.",
    "Joke #109: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #110: Chuck Norris can divide by zero.",
    "Joke #111: Chuck Norris counted to infinity. Twice.",
    "Joke #112: Chuck Norris can slam a revolving door.",
    "Joke #113: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #114: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #115: Chuck Norris doesn't sleep. He waits.",
    "Joke #116: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #117: Chuck Norris can build a snowman out of rain.",
    "Joke #118: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #119: Chuck Norris can hear sign language.",
    "Joke #120: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #121: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #122: Chuck Norris can divide by zero.",
    "Joke #123: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #124: Chuck Norris can slam a revolving door.",
    "Joke #125: Chuck Norris can unscramble an egg.",
    "Joke #126: Chuck Norris can believe it's not butter.",
    "Joke #127: Chuck Norris can hear sign language.",
    "Joke #128: Chuck Norris counted to infinity. Twice.",
    "Joke #129: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #130: Chuck Norris can divide by zero.",
    "Joke #131: Chuck Norris counted to infinity. Twice.",
    "Joke #132: Chuck Norris can slam a revolving door.",
    "Joke #133: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #134: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #135: Chuck Norris doesn't sleep. He waits.",
    "Joke #136: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #137: Chuck Norris can build a snowman out of rain.",
    "Joke #138: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #139: Chuck Norris can hear sign language.",
    "Joke #140: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #141: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #142: Chuck Norris can divide by zero.",
    "Joke #143: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #144: Chuck Norris can slam a revolving door.",
    "Joke #145: Chuck Norris can unscramble an egg.",
    "Joke #146: Chuck Norris can believe it's not butter.",
    "Joke #147: Chuck Norris can hear sign language.",
    "Joke #148: Chuck Norris counted to infinity. Twice.",
    "Joke #149: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #150: Chuck Norris can divide by zero.",
    "Joke #151: Chuck Norris counted to infinity. Twice.",
    "Joke #152: Chuck Norris can slam a revolving door.",
    "Joke #153: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #154: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #155: Chuck Norris doesn't sleep. He waits.",
    "Joke #156: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #157: Chuck Norris can build a snowman out of rain.",
    "Joke #158: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #159: Chuck Norris can hear sign language.",
    "Joke #160: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #161: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #162: Chuck Norris can divide by zero.",
    "Joke #163: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #164: Chuck Norris can slam a revolving door.",
    "Joke #165: Chuck Norris can unscramble an egg.",
    "Joke #166: Chuck Norris can believe it's not butter.",
    "Joke #167: Chuck Norris can hear sign language.",
    "Joke #168: Chuck Norris counted to infinity. Twice.",
    "Joke #169: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #170: Chuck Norris can divide by zero.",
    "Joke #171: Chuck Norris counted to infinity. Twice.",
    "Joke #172: Chuck Norris can slam a revolving door.",
    "Joke #173: When Chuck Norris does a push-up, he's not lifting himself up; he's pushing the Earth down.",
    "Joke #174: Chuck Norris doesn't do push-ups. He pushes the Earth down.",
    "Joke #175: Chuck Norris doesn't sleep. He waits.",
    "Joke #176: When the Boogeyman goes to bed, he checks his closet for Chuck Norris.",
    "Joke #177: Chuck Norris can build a snowman out of rain.",
    "Joke #178: The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Joke #179: Chuck Norris can hear sign language.",
    "Joke #180: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #181: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #182: Chuck Norris can divide by zero.",
    "Joke #183: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #184: Chuck Norris can slam a revolving door.",
    "Joke #185: Chuck Norris can unscramble an egg.",
    "Joke #186: Chuck Norris can believe it's not butter.",
    "Joke #187: Chuck Norris can hear sign language.",
    "Joke #188: Chuck Norris counted to infinity. Twice.",
    "Joke #189: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #190: Chuck Norris can divide by zero.",
    "Joke #191: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #191: The reason the Holy Grail has never been recovered is that nobody is brave enough to ask Chuck Norris to give up his favorite coffee mug.",
    "Joke #192: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Joke #193: Chuck Norris can divide by zero.",
    "Joke #194: When Chuck Norris plays Sudoku, the numbers just fall into place out of fear.",
    "Joke #195: Chuck Norris can slam a revolving door.",
    "Joke #196: Chuck Norris can unscramble an egg.",
    "Joke #197: Chuck Norris can believe it's not butter.",
    "Joke #198: Chuck Norris can hear sign language.",
    "Joke #199: Chuck Norris counted to infinity. Twice.",
    "Joke #200: When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off."
];


function fetchJokes() {
    const startIndex = (page - 1) * jokesPerPage;
    const endIndex = Math.min(startIndex + jokesPerPage, totalJokes);
    const jokesToDisplay = customJokes.slice(startIndex, endIndex);
    displayJokes(jokesToDisplay);
}

function displayJokes(jokes) {
    jokes.forEach((joke) => {
        const jokeElement = document.createElement('div');
        jokeElement.classList.add('joke');
        jokeElement.textContent = joke;
        jokesContainer.appendChild(jokeElement);
    });
}

function loadMoreJokes() {
    if (page * jokesPerPage <= totalJokes) {
        fetchJokes();
        page++;
    }
}

window.addEventListener('scroll', () => {
    const { scrollTop, scrollHeight, clientHeight } = document.documentElement;
    if (scrollTop + clientHeight >= scrollHeight - 5) {
        loadMoreJokes();
    }
});

// Initial load
loadMoreJokes();
